version: "3.7"

services:
  disasm_app:
    build: .
    volumes:
      - ./files:/usr/src/files
      - ./results:/usr/src/results
      - ./extracted_archives:/usr/src/extracted_archives
    command: "python3 main.py"
