version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
    ports:
      - "5672:5672"

  celery_app:
    build: .
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq
    command: "celery -A tasks worker -l info -P gevent"

  disasm_app:
    build: .
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
    volumes:
      - ./app:/usr/src/app
      - ./files:/usr/src/files
      - ./results:/usr/src/results
      - ./extracted_archives:/usr/src/extracted_archives
    command: "python3 main.py"
