import os

# Different folder paths
PATH_OF_RESULTS_FOLDER = "../results/"
PATH_OF_EXTRACTED_ARCHIVES_FOLDER = "../extracted_archives/"

NAME_OF_EXTRACTED_ARCHIVES_FOLDER = PATH_OF_EXTRACTED_ARCHIVES_FOLDER[::-1]
NAME_OF_EXTRACTED_ARCHIVES_FOLDER = NAME_OF_EXTRACTED_ARCHIVES_FOLDER[1:NAME_OF_EXTRACTED_ARCHIVES_FOLDER.find(
    "/", 1)]
NAME_OF_EXTRACTED_ARCHIVES_FOLDER = NAME_OF_EXTRACTED_ARCHIVES_FOLDER[::-1]


# RabbitMQ constants
RABBITMQ_HOST = os.environ.get('RABBITMQ_HOST')
RABBITMQ_USERNAME = os.environ.get('RABBITMQ_USERNAME')
RABBITMQ_PASSWORD = os.environ.get('RABBITMQ_PASSWORD')
RABBITMQ_PORT = os.environ.get('RABBITMQ_PORT')

BROKER_CONN_URI = f"amqp://{RABBITMQ_USERNAME}:{RABBITMQ_PASSWORD}@{RABBITMQ_HOST}:{RABBITMQ_PORT}"
